### ISSUE TITLE
Inkdrop has a blank area

### ISSUE THREAD

**Issue by aviscaerulea** [basyura/inkdrop-sidetoc#6]
The issue is that I get a blank area in the lower left corner of Inkdrop as shown in the attached image, which does not disappear until I restart or reload Inkdrop.

It disappears when I turn off sitetoc with `Ctrl + L`, so I thought it might be a factor in sidetoc.

In most cases, this issue occurs when scrolling down a note.
This may be especially true if I am scrolling down further at the end of the note.

Windows 10 Pro 2004
Inkdrop v5.2.1
sitetoc v1.10.0

sidetoc settings
highlight color: #C5EAFB
side pane width: 200
increase pane widh: 10

![20210121_093258](https://user-images.githubusercontent.com/1040522/105258145-72a7fd00-5bcc-11eb-9f66-0c7d5e8fbb12.png)

**Comment by basyura** [comment]
Thank you for reporting!

I think it's because the sidetoc's height calculation failed.

https://github.com/basyura/inkdrop-sidetoc/blob/master/src/sidetoc-pane.tsx#L126

```js
const style = {
  fontFamily: Settings.fontFamily,
  height:
    inkdrop.window.getSize()[1] -
    this.paneState.heightDiff -
    (statusBar != null ? statusBar.clientHeight : 0),
};
```

`heightDiff` is this.

```js
const winHeight = inkdrop.window.getSize()[1];
this.paneState.heightDiff = winHeight - cm.getScrollInfo().clientHeight;
```

Can you tell me a text that causes the problem ?  
It doesn't matter what the content is. Even with "aaaa" and "bbbb".

**Comment by basyura** [comment]
I think we probably have this problem solved, so I'll close it.
